config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'searches#index'
  resources :searches, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def index
    response = InformationFinder.call(params)
    flash.clear
    unless response[:success]
      flash[:notice] = "Search for your favourite Play! Nothing to show now."
    else
      @result = response[:data]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when 'notice' then "alert alert-info"
    when 'success' then "alert alert-success"
    when 'error' then "alert alert-error"
    when 'alert' then "alert alert-error"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchService</title>
    <%= csrf_meta_tags %>
    <%#= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/searches/_flash.html.erb
<% flash.each do |key, value| %>
  <div role="alert" class="<%= flash_class(key) %>">
    <%= value %>
  </div>
<% end %>

app/views/searches/_results.html.erb
<table class="table">
  <thead>
  <tr>
    <th scope="col">#</th>
    <th scope="col">Title</th>
    <th scope="col">Year</th>
    <th scope="col">Poster</th>
  </tr>
  </thead>
  <tbody>
  <% @result.each_with_index do |res, i| %>
    <tr>
      <th scope="row"><%= i+1 %></th>
      <td><%= res.title %></td>
      <td><%= res.year %></td>
      <td><%= image_tag res.poster, size: '80x80' if res.poster != 'N/A' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/searches/index.html.erb
<div class="container">

<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href='/'>Search Information</a>
    <%= form_tag searches_path, method: 'get', class: 'form-inline', role: 'searches' do %>
      <%= text_field_tag :title, params[:title], placeholder: "By Title", class: "form-control mr-sm-2" %>
      <%= text_field_tag :year, params[:year], placeholder: "By Year", class: "form-control mr-sm-2" %>
      <%= submit_tag 'Search', class: 'btn btn-outline-success my-2 my-sm-0' %>
    <% end %>
</nav>
  <% if flash.present? %>
    <%= render 'flash' %>
  <% else %>
   <% unless @result %>
    <div class="alert alert-info" role="alert">
      Search for your favourite Play! Nothing to show now.
    </div>
   <% else %>
    <%= render 'results' %>
   <% end %>
  <% end %>

</div>